// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExchange creates a new instance of MockExchange. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExchange(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExchange {
	mock := &MockExchange{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExchange is an autogenerated mock type for the Exchange type
type MockExchange struct {
	mock.Mock
}

type MockExchange_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExchange) EXPECT() *MockExchange_Expecter {
	return &MockExchange_Expecter{mock: &_m.Mock}
}

// ReceiveChallenge provides a mock function for the type MockExchange
func (_mock *MockExchange) ReceiveChallenge(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveChallenge")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExchange_ReceiveChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveChallenge'
type MockExchange_ReceiveChallenge_Call struct {
	*mock.Call
}

// ReceiveChallenge is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExchange_Expecter) ReceiveChallenge(ctx any) *MockExchange_ReceiveChallenge_Call {
	return &MockExchange_ReceiveChallenge_Call{Call: _e.mock.On("ReceiveChallenge", ctx)}
}

func (_c *MockExchange_ReceiveChallenge_Call) Run(run func(ctx context.Context)) *MockExchange_ReceiveChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExchange_ReceiveChallenge_Call) Return(bytes []byte, err error) *MockExchange_ReceiveChallenge_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockExchange_ReceiveChallenge_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockExchange_ReceiveChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// SendPayload provides a mock function for the type MockExchange
func (_mock *MockExchange) SendPayload(ctx context.Context, payload []byte) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for SendPayload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExchange_SendPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPayload'
type MockExchange_SendPayload_Call struct {
	*mock.Call
}

// SendPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *MockExchange_Expecter) SendPayload(ctx any, payload any) *MockExchange_SendPayload_Call {
	return &MockExchange_SendPayload_Call{Call: _e.mock.On("SendPayload", ctx, payload)}
}

func (_c *MockExchange_SendPayload_Call) Run(run func(ctx context.Context, payload []byte)) *MockExchange_SendPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExchange_SendPayload_Call) Return(err error) *MockExchange_SendPayload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExchange_SendPayload_Call) RunAndReturn(run func(ctx context.Context, payload []byte) error) *MockExchange_SendPayload_Call {
	_c.Call.Return(run)
	return _c
}

// SendResponse provides a mock function for the type MockExchange
func (_mock *MockExchange) SendResponse(ctx context.Context, response []byte) error {
	ret := _mock.Called(ctx, response)

	if len(ret) == 0 {
		panic("no return value specified for SendResponse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExchange_SendResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResponse'
type MockExchange_SendResponse_Call struct {
	*mock.Call
}

// SendResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - response []byte
func (_e *MockExchange_Expecter) SendResponse(ctx any, response any) *MockExchange_SendResponse_Call {
	return &MockExchange_SendResponse_Call{Call: _e.mock.On("SendResponse", ctx, response)}
}

func (_c *MockExchange_SendResponse_Call) Run(run func(ctx context.Context, response []byte)) *MockExchange_SendResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExchange_SendResponse_Call) Return(err error) *MockExchange_SendResponse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExchange_SendResponse_Call) RunAndReturn(run func(ctx context.Context, response []byte) error) *MockExchange_SendResponse_Call {
	_c.Call.Return(run)
	return _c
}
