// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/componere/incus-spire-attestor/internal/attest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGuestEvidence creates a new instance of MockGuestEvidence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuestEvidence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuestEvidence {
	mock := &MockGuestEvidence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGuestEvidence is an autogenerated mock type for the GuestEvidence type
type MockGuestEvidence struct {
	mock.Mock
}

type MockGuestEvidence_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuestEvidence) EXPECT() *MockGuestEvidence_Expecter {
	return &MockGuestEvidence_Expecter{mock: &_m.Mock}
}

// Claims provides a mock function for the type MockGuestEvidence
func (_mock *MockGuestEvidence) Claims(ctx context.Context) (attest.Claims, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Claims")
	}

	var r0 attest.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (attest.Claims, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) attest.Claims); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(attest.Claims)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuestEvidence_Claims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claims'
type MockGuestEvidence_Claims_Call struct {
	*mock.Call
}

// Claims is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGuestEvidence_Expecter) Claims(ctx any) *MockGuestEvidence_Claims_Call {
	return &MockGuestEvidence_Claims_Call{Call: _e.mock.On("Claims", ctx)}
}

func (_c *MockGuestEvidence_Claims_Call) Run(run func(ctx context.Context)) *MockGuestEvidence_Claims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGuestEvidence_Claims_Call) Return(claims attest.Claims, err error) *MockGuestEvidence_Claims_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockGuestEvidence_Claims_Call) RunAndReturn(run func(ctx context.Context) (attest.Claims, error)) *MockGuestEvidence_Claims_Call {
	_c.Call.Return(run)
	return _c
}

// ReadConfig provides a mock function for the type MockGuestEvidence
func (_mock *MockGuestEvidence) ReadConfig(ctx context.Context, key attest.ConfigKey) (string, bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ReadConfig")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, attest.ConfigKey) (string, bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, attest.ConfigKey) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, attest.ConfigKey) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, attest.ConfigKey) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGuestEvidence_ReadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadConfig'
type MockGuestEvidence_ReadConfig_Call struct {
	*mock.Call
}

// ReadConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - key attest.ConfigKey
func (_e *MockGuestEvidence_Expecter) ReadConfig(ctx any, key any) *MockGuestEvidence_ReadConfig_Call {
	return &MockGuestEvidence_ReadConfig_Call{Call: _e.mock.On("ReadConfig", ctx, key)}
}

func (_c *MockGuestEvidence_ReadConfig_Call) Run(run func(ctx context.Context, key attest.ConfigKey)) *MockGuestEvidence_ReadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 attest.ConfigKey
		if args[1] != nil {
			arg1 = args[1].(attest.ConfigKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuestEvidence_ReadConfig_Call) Return(value string, found bool, err error) *MockGuestEvidence_ReadConfig_Call {
	_c.Call.Return(value, found, err)
	return _c
}

func (_c *MockGuestEvidence_ReadConfig_Call) RunAndReturn(run func(ctx context.Context, key attest.ConfigKey) (string, bool, error)) *MockGuestEvidence_ReadConfig_Call {
	_c.Call.Return(run)
	return _c
}
