site_name: incus-spire-attestor
site_description: Incus SPIRE NodeAttestor plugins
site_url: https://componere.github.io/incus-spire-attestor/
repo_name: componere/incus-spire-attestor
repo_url: https://github.com/componere/incus-spire-attestor
edit_uri: edit/master/docs/docs/
docs_dir: docs
site_dir: build
strict: true

theme:
  name: material
  language: en
  features:
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Deploy: how-to/deploy.md
  - Configuration: reference/configuration.md
  - Security model: explanation/security-model.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - stylesheets/palette.css
