// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/componere/incus-spire-attestor/internal/attest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExchange creates a new instance of MockExchange. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExchange(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExchange {
	mock := &MockExchange{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExchange is an autogenerated mock type for the Exchange type
type MockExchange struct {
	mock.Mock
}

type MockExchange_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExchange) EXPECT() *MockExchange_Expecter {
	return &MockExchange_Expecter{mock: &_m.Mock}
}

// ReceivePayload provides a mock function for the type MockExchange
func (_mock *MockExchange) ReceivePayload(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReceivePayload")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExchange_ReceivePayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceivePayload'
type MockExchange_ReceivePayload_Call struct {
	*mock.Call
}

// ReceivePayload is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExchange_Expecter) ReceivePayload(ctx any) *MockExchange_ReceivePayload_Call {
	return &MockExchange_ReceivePayload_Call{Call: _e.mock.On("ReceivePayload", ctx)}
}

func (_c *MockExchange_ReceivePayload_Call) Run(run func(ctx context.Context)) *MockExchange_ReceivePayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExchange_ReceivePayload_Call) Return(bytes []byte, err error) *MockExchange_ReceivePayload_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockExchange_ReceivePayload_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockExchange_ReceivePayload_Call {
	_c.Call.Return(run)
	return _c
}

// ReceiveResponse provides a mock function for the type MockExchange
func (_mock *MockExchange) ReceiveResponse(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveResponse")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExchange_ReceiveResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveResponse'
type MockExchange_ReceiveResponse_Call struct {
	*mock.Call
}

// ReceiveResponse is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExchange_Expecter) ReceiveResponse(ctx any) *MockExchange_ReceiveResponse_Call {
	return &MockExchange_ReceiveResponse_Call{Call: _e.mock.On("ReceiveResponse", ctx)}
}

func (_c *MockExchange_ReceiveResponse_Call) Run(run func(ctx context.Context)) *MockExchange_ReceiveResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExchange_ReceiveResponse_Call) Return(bytes []byte, err error) *MockExchange_ReceiveResponse_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockExchange_ReceiveResponse_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockExchange_ReceiveResponse_Call {
	_c.Call.Return(run)
	return _c
}

// SendAttributes provides a mock function for the type MockExchange
func (_mock *MockExchange) SendAttributes(ctx context.Context, attrs attest.Attributes) error {
	ret := _mock.Called(ctx, attrs)

	if len(ret) == 0 {
		panic("no return value specified for SendAttributes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, attest.Attributes) error); ok {
		r0 = returnFunc(ctx, attrs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExchange_SendAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAttributes'
type MockExchange_SendAttributes_Call struct {
	*mock.Call
}

// SendAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - attrs attest.Attributes
func (_e *MockExchange_Expecter) SendAttributes(ctx any, attrs any) *MockExchange_SendAttributes_Call {
	return &MockExchange_SendAttributes_Call{Call: _e.mock.On("SendAttributes", ctx, attrs)}
}

func (_c *MockExchange_SendAttributes_Call) Run(run func(ctx context.Context, attrs attest.Attributes)) *MockExchange_SendAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 attest.Attributes
		if args[1] != nil {
			arg1 = args[1].(attest.Attributes)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExchange_SendAttributes_Call) Return(err error) *MockExchange_SendAttributes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExchange_SendAttributes_Call) RunAndReturn(run func(ctx context.Context, attrs attest.Attributes) error) *MockExchange_SendAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// SendChallenge provides a mock function for the type MockExchange
func (_mock *MockExchange) SendChallenge(ctx context.Context, challenge []byte) error {
	ret := _mock.Called(ctx, challenge)

	if len(ret) == 0 {
		panic("no return value specified for SendChallenge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, challenge)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExchange_SendChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendChallenge'
type MockExchange_SendChallenge_Call struct {
	*mock.Call
}

// SendChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - challenge []byte
func (_e *MockExchange_Expecter) SendChallenge(ctx any, challenge any) *MockExchange_SendChallenge_Call {
	return &MockExchange_SendChallenge_Call{Call: _e.mock.On("SendChallenge", ctx, challenge)}
}

func (_c *MockExchange_SendChallenge_Call) Run(run func(ctx context.Context, challenge []byte)) *MockExchange_SendChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExchange_SendChallenge_Call) Return(err error) *MockExchange_SendChallenge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExchange_SendChallenge_Call) RunAndReturn(run func(ctx context.Context, challenge []byte) error) *MockExchange_SendChallenge_Call {
	_c.Call.Return(run)
	return _c
}
