// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/componere/incus-spire-attestor/internal/attest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIncus creates a new instance of MockIncus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncus {
	mock := &MockIncus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncus is an autogenerated mock type for the Incus type
type MockIncus struct {
	mock.Mock
}

type MockIncus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncus) EXPECT() *MockIncus_Expecter {
	return &MockIncus_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function for the type MockIncus
func (_mock *MockIncus) Lookup(ctx context.Context, project attest.ProjectName, name attest.InstanceName) (attest.Instance, bool, error) {
	ret := _mock.Called(ctx, project, name)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 attest.Instance
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, attest.ProjectName, attest.InstanceName) (attest.Instance, bool, error)); ok {
		return returnFunc(ctx, project, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, attest.ProjectName, attest.InstanceName) attest.Instance); ok {
		r0 = returnFunc(ctx, project, name)
	} else {
		r0 = ret.Get(0).(attest.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, attest.ProjectName, attest.InstanceName) bool); ok {
		r1 = returnFunc(ctx, project, name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, attest.ProjectName, attest.InstanceName) error); ok {
		r2 = returnFunc(ctx, project, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIncus_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockIncus_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - ctx context.Context
//   - project attest.ProjectName
//   - name attest.InstanceName
func (_e *MockIncus_Expecter) Lookup(ctx any, project any, name any) *MockIncus_Lookup_Call {
	return &MockIncus_Lookup_Call{Call: _e.mock.On("Lookup", ctx, project, name)}
}

func (_c *MockIncus_Lookup_Call) Run(run func(ctx context.Context, project attest.ProjectName, name attest.InstanceName)) *MockIncus_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 attest.ProjectName
		if args[1] != nil {
			arg1 = args[1].(attest.ProjectName)
		}
		var arg2 attest.InstanceName
		if args[2] != nil {
			arg2 = args[2].(attest.InstanceName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIncus_Lookup_Call) Return(instance attest.Instance, found bool, err error) *MockIncus_Lookup_Call {
	_c.Call.Return(instance, found, err)
	return _c
}

func (_c *MockIncus_Lookup_Call) RunAndReturn(run func(ctx context.Context, project attest.ProjectName, name attest.InstanceName) (attest.Instance, bool, error)) *MockIncus_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// SetNonce provides a mock function for the type MockIncus
func (_mock *MockIncus) SetNonce(ctx context.Context, instance attest.Instance, key attest.ConfigKey, nonce string) error {
	ret := _mock.Called(ctx, instance, key, nonce)

	if len(ret) == 0 {
		panic("no return value specified for SetNonce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, attest.Instance, attest.ConfigKey, string) error); ok {
		r0 = returnFunc(ctx, instance, key, nonce)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncus_SetNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNonce'
type MockIncus_SetNonce_Call struct {
	*mock.Call
}

// SetNonce is a helper method to define mock.On call
//   - ctx context.Context
//   - instance attest.Instance
//   - key attest.ConfigKey
//   - nonce string
func (_e *MockIncus_Expecter) SetNonce(ctx any, instance any, key any, nonce any) *MockIncus_SetNonce_Call {
	return &MockIncus_SetNonce_Call{Call: _e.mock.On("SetNonce", ctx, instance, key, nonce)}
}

func (_c *MockIncus_SetNonce_Call) Run(run func(ctx context.Context, instance attest.Instance, key attest.ConfigKey, nonce string)) *MockIncus_SetNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 attest.Instance
		if args[1] != nil {
			arg1 = args[1].(attest.Instance)
		}
		var arg2 attest.ConfigKey
		if args[2] != nil {
			arg2 = args[2].(attest.ConfigKey)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIncus_SetNonce_Call) Return(err error) *MockIncus_SetNonce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncus_SetNonce_Call) RunAndReturn(run func(ctx context.Context, instance attest.Instance, key attest.ConfigKey, nonce string) error) *MockIncus_SetNonce_Call {
	_c.Call.Return(run)
	return _c
}

// UnsetNonce provides a mock function for the type MockIncus
func (_mock *MockIncus) UnsetNonce(ctx context.Context, instance attest.Instance, key attest.ConfigKey) error {
	ret := _mock.Called(ctx, instance, key)

	if len(ret) == 0 {
		panic("no return value specified for UnsetNonce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, attest.Instance, attest.ConfigKey) error); ok {
		r0 = returnFunc(ctx, instance, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncus_UnsetNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsetNonce'
type MockIncus_UnsetNonce_Call struct {
	*mock.Call
}

// UnsetNonce is a helper method to define mock.On call
//   - ctx context.Context
//   - instance attest.Instance
//   - key attest.ConfigKey
func (_e *MockIncus_Expecter) UnsetNonce(ctx any, instance any, key any) *MockIncus_UnsetNonce_Call {
	return &MockIncus_UnsetNonce_Call{Call: _e.mock.On("UnsetNonce", ctx, instance, key)}
}

func (_c *MockIncus_UnsetNonce_Call) Run(run func(ctx context.Context, instance attest.Instance, key attest.ConfigKey)) *MockIncus_UnsetNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 attest.Instance
		if args[1] != nil {
			arg1 = args[1].(attest.Instance)
		}
		var arg2 attest.ConfigKey
		if args[2] != nil {
			arg2 = args[2].(attest.ConfigKey)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIncus_UnsetNonce_Call) Return(err error) *MockIncus_UnsetNonce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncus_UnsetNonce_Call) RunAndReturn(run func(ctx context.Context, instance attest.Instance, key attest.ConfigKey) error) *MockIncus_UnsetNonce_Call {
	_c.Call.Return(run)
	return _c
}
